version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - weather_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - weather_net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # ← CORRIGÉ : pas de underscore dans le nom
    networks:
      - weather_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - weather_net

  producer:
    build: ./producer # ← "Construis une image à partir du dossier ./producer"
    depends_on:
      - kafka
    networks:
      - weather_net

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - postgres
    networks:
      - weather_net
    restart: on-failure

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    networks:
      - weather_net

volumes:
  postgres_data:  # ← juste le nom, pas de chemin, pas d'underscore incorrect

networks:
  weather_net:
    name: weather_net
    driver: bridge